sudo: required

services: 
  - docker

before_install: 
  - docker build -t brandonjones085/docker-react -f Dockerfile.dev .

script:
  - docker run brandonjones085/docker-react npm run test -- --coverage

