sudo: required

services: 
  - docker

before_install: 
  - docker build -t brandonjones085/docker-react -f Dockerfile.dev .

script:
  - docker run brandonjones085/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-243279705396"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $ACCESS_KEY
  secret_access_key: 
    secure: $SECRET_KEY
  